[package]
version = "0.1.0"
name = "swiftness-program"
edition = "2021"

[dependencies]
sp1-zkvm = "2.0.0"
serde_json = { version = "1.0.114", default-features = false }

swiftness = { workspace = true }
swiftness_air = { workspace = true }
